### ISSUE TITLE
Bitwarden crashed when disabled biometrics.

### ISSUE THREAD

**Issue by nikhilbadyal** [bitwarden/android#1294]
Here is the stack trace. Ik the the cause but still the crash must be handled well.

Reinstall is the only option I can see now.

**Crash as captured by OS. **
https://del.dog/hilovuppyw.txt

**Copy paste**

time: 1614697929515
msg: java.security.UnrecoverableKeyException: User changed or deleted their auth credentials
stacktrace: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	... 1 more
Caused by: java.security.UnrecoverableKeyException: User changed or deleted their auth credentials
	at android.security.keystore.AndroidKeyStoreSpi.engineGetKey(AndroidKeyStoreSpi.java:109)
	at java.security.KeyStore.getKey(KeyStore.java:1062)
	at crc64720bb2db43a66fe9.NavigationPageRenderer.n_onAttachedToWindow(Native Method)
	at crc64720bb2db43a66fe9.NavigationPageRenderer.onAttachedToWindow(NavigationPageRenderer.java:49)
	at android.view.View.dispatchAttachedToWindow(View.java:20479)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3489)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3496)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3496)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3496)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3496)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3496)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3496)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3496)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2435)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1948)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8182)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
	at android.view.Choreographer.doFrame(Choreographer.java:731)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
	... 3 more

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1294
