### ISSUE TITLE
App crushing 

### ISSUE THREAD

**Issue by rajarshikhatua100** [bitwarden/android#1966]
### Steps To Reproduce

1. On low internet connection (under 100 kb)
2.  tap on sync
3. after completing ; tap any of the logins

### Expected Result

Open the account login page

### Actual Result

app crushing 

### Screenshots or Videos

didn't took one

### Additional Context

Log - 

FATAL EXCEPTION: main
Process: com.x8bit.bitwarden, PID: 8205
android.runtime.JavaProxyThrowable: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
  at System.Collections.Generic.List`1[T].get_Item (System.Int32 index) [0x00009] in <65af44f147af4e1ea969fd6f016fa021>:0 
  at System.Collections.Generic.List`1[T].System.Collections.IList.get_Item (System.Int32 index) [0x00000] in <65af44f147af4e1ea969fd6f016fa021>:0 
  at Xamarin.Forms.Platform.Android.ObservableItemsSource.ElementAt (System.Int32 index) [0x0000f] in <a62e492d2a9c482aa07a5a905a0d7044>:0 
  at Xamarin.Forms.Platform.Android.ObservableItemsSource.GetItem (System.Int32 position) [0x00008] in <a62e492d2a9c482aa07a5a905a0d7044>:0 
  at Xamarin.Forms.Platform.Android.UngroupedItemsSource.GetItem (System.Int32 position) [0x00000] in <a62e492d2a9c482aa07a5a905a0d7044>:0 
  at Xamarin.Forms.Platform.Android.SelectableItemsViewAdapter`2[TItemsView,TItemsSource].UpdateFormsSelection (System.Int32 adapterPosition) [0x00025] in <a62e492d2a9c482aa07a5a905a0d7044>:0 
  at Xamarin.Forms.Platform.Android.SelectableItemsViewAdapter`2[TItemsView,TItemsSource].SelectableClicked (System.Object sender, System.Int32 adapterPosition) [0x00000] in <a62e492d2a9c482aa07a5a905a0d7044>:0 
  at Xamarin.Forms.Platform.Android.SelectableViewHolder.OnViewHolderClicked (System.Int32 adapterPosition) [0x0000a] in <a62e492d2a9c482aa07a5a905a0d7044>:0 
  at Xamarin.Forms.Platform.Android.SelectableViewHolder.OnClick (Android.Views.View view) [0x0000f] in <a62e492d2a9c482aa07a5a905a0d7044>:0 
  at Android.Views.View+IOnClickListenerInvoker.n_OnClick_Landroid_view_View_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_v) [0x0000f] in <f8dad6efcab248969e7288e0cc40ecd7>:0 
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.74(intptr,intptr,intptr)
	at crc643f46942d9dd1fff9.SelectableViewHolder.n_onClick(Native Method)
	at crc643f46942d9dd1fff9.SelectableViewHolder.onClick(SelectableViewHolder.java:30)
	at android.view.View.performClick(View.java:7792)
	at android.view.View.performClickInternal(View.java:7769)
	at android.view.View.access$3800(View.java:910)
	at android.view.View$PerformClick.run(View.java:30218)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

### Operating System

Android

### Operating System Version

Android 12

### Device

Samsung galaxy m 31

### Build Version

2022.05.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1966
