### ISSUE TITLE
No autofill on android 10

### ISSUE THREAD

**Issue by farfromrefug** [bitwarden/android#3640]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

On Android 10 the autofill option appears in the text field context menus but it does nothing. 
To be clear there is no autofill working on android 10

### Expected Result

Autofill working

### Actual Result

Not working

### Build Version

2024.7.2

### Environment Details

Android 10
LineageOS

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @farfromrefug,

Thank you for this report.
1. Could you please attach screenshots that show how the Settings > Auto-fill menu is configured?
2. Could you please clarify what you meant by "On Android 10 the autofill option appears in the text field context menus but it does nothing."? Which autofill function are you referring to exactly? To be clear, they're all listed [here](https://bitwarden.com/help/auto-fill-android/).

Thank you,

**Comment by farfromrefug** [comment]
@SergeantConfused Here are the screenshots.
The second one shows you the autofill option i am talking about.
2 remarks:
* i dont see the "overlay" i get with the old app to autofill a textfield. I think you did not implement it yet as the app does not ask for draw over apps permissions
* if i click on the autofill button shown in the second screenshot and immediately switch to the new bitwarden app i see the app is frozen for about 5 seconds. After that the app works again but nothing happened ( not auto fill)
![Screenshot_20240801-101516_Bitwarden_Beta](https://github.com/user-attachments/assets/c34a10e9-7625-4138-84ec-3f80b56aa885)
![Screenshot_20240801-101550_Aurora_Store](https://github.com/user-attachments/assets/81ef6103-40f9-414f-8553-067b03fe1bbd)

**Comment by Ehab-d** [comment]
I'm on Android 10 too and I can confirm that. Sometimes it happens and sometimes it doesn't. It can be said that the auto-fill is very buggy. Note: I've tried another password manager and the auto-fill works well.

**Comment by ganjiayi** [comment]
Yes,I think it is a bug.

**Comment by closebot-bw** [comment]
⚠️ **Stale Issue Notice**

This issue has been automatically marked as stale due to inactivity. It will be closed in **2 weeks** (August 26, 2025) if no further activity occurs.

If this issue is still relevant and you would like to keep it open, please:
- Comment on this issue to show continued interest
- Provide any additional information or updates
- Confirm that the issue still exists in the latest version

Thank you for your contribution to this project! 🙏

**Comment by jasoncot** [comment]
I am encountering this when trying to autofill on android 10 within other apps.  It seems to work correctly in Chrome, but no autofill prompt/suggestion in other apps.

After digging through the help pages, I see that one of the suggestions is to ...
> If the Bitwarden autofill service overlay isn't visible when your device is focusing on a username or password input field, your device may require a device-specific setting to be enabled:
> https://bitwarden.com/help/auto-fill-android-troubleshooting/

But I am unable to enable the "Floating Window" or "Display over other apps" for Bitwarden, since it is not on the list of apps to grant.

I've tried granting it via adb:
```bash
adb shell pm grant com.x8bit.bitwarden android.permission.SYSTEM_ALERT_WINDOW
```

but I get an error, roughly stating that the app isn't asking for the permission.
```
Security exception: Package com.x8bit.bitwarden has not requested permission android.permission.SYSTEM_ALERT_WINDOW

java.lang.SecurityException: Package com.x8bit.bitwarden has not requested permission android.permission.SYSTEM_ALERT_WINDOW
        at com.android.server.pm.permission.BasePermission.enforceDeclaredUsedAndRuntimeOrDevelopment(BasePermission.java:444)
        at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:2245)
        at com.android.server.pm.permission.PermissionManagerService.access$1100(PermissionManagerService.java:124)
        at com.android.server.pm.permission.PermissionManagerService$PermissionManagerServiceInternalImpl.grantRuntimePermission(PermissionManagerService.java:3283)
        at com.android.server.pm.PackageManagerService.grantRuntimePermission(PackageManagerService.java:5949)
        at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(PackageManagerShellCommand.java:1985)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:230)
        at android.os.ShellCommand.exec(ShellCommand.java:104)
        at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:22414)
        at android.os.Binder.shellCommand(Binder.java:890)
        at android.os.Binder.onTransact(Binder.java:774)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4880)
        at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4213)
        at android.os.Binder.execTransactInternal(Binder.java:1036)
        at android.os.Binder.execTransact(Binder.java:1003)
```

is it possible to get a build of the app for android 10 that requests the permission so it can be granted?
