### ISSUE TITLE
Beta APP cannot be run

### ISSUE THREAD

**Issue by likevi9528** [bitwarden/android#3763]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. click https://github.com/bitwarden/android/actions/workflows/build.yml
2. Setup and Click APP Icon

The Beta APKs generated by these 8 workflows or newer(maybe) cannot be run.

### Expected Result

Normal operation

### Actual Result

Crash, can't run normally

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/79a76db1-89e1-4f85-9db4-a017ed489cfc)
![1723827309954](https://github.com/user-attachments/assets/3df87788-e86d-4c1c-954a-525ab93e1318)

### Additional Context

java.lang.RuntimeException: Unable to create application com.x8bit.bitwarden.BitwardenApplication: java.lang.ClassCastException
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7103)
	at android.app.ActivityThread.access$1600(ActivityThread.java:273)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2125)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8258)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
Caused by: java.lang.ClassCastException
	at W.g0.x(Unknown Source:2)
	at B7.a.f(Unknown Source:62)
	at O5.s.get(Unknown Source:3979)
	at sa.a.get(Unknown Source:13)
	at O5.s.get(Unknown Source:3985)
	at sa.a.get(Unknown Source:13)
	at O5.s.get(Unknown Source:4170)
	at sa.a.get(Unknown Source:13)
	at com.x8bit.bitwarden.BitwardenApplication.onCreate(Unknown Source:19)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1223)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7097)
	... 9 more

### Build Version

2024.8.1

### Environment Details

Android 12
Redmi K30

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cbbit** [comment]
Hi,

Thank you for your report! It has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by likevi9528** [comment]
beat app 19039 version runs ok.
