### ISSUE TITLE
Auto fill crash

### ISSUE THREAD

**Issue by Bazixv13** [bitwarden/android#3855]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Go to v3.account.samsung.com 
2. Click on Login
3. press the auto fill suggestion for password
4. Click on the back arrow as if you typed in the wrong mail
5. repeat process 2-4 times untill app crashes when clicking on autofill

### Expected Result

app auto fills the password or email

### Actual Result

app not auto filling the password / email (depends on which step error happens) and crashing also thing that is interesting it crashes the app in which the auto fill was used ex chrome in my case

### Screenshots or Videos

https://github.com/user-attachments/assets/ff210426-7819-49c0-94f0-fd4d1204a0be

### Additional Context

**Crash report / crash logs** (_copied using Google lens so also attached the screenshots if something was not correctly copied_):
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Class.isInterface()' on a null object reference at java.lang.Class.isAssignable From (Class.java:824)

at

android.os.Parcel.read ParcelableCreatorInternal(Parcel.jav a:4853)

at

android.os.Parcel.read ParcelableInternal(Parcel.java:4766) at android.os.Parcel.readValue (Parcel.java:4532)

at android.os.Parcel.readValue (Parcel.java:4312) at android.os.Parcel.-$$Nest$mreadValue(Unknown

Source:0)

at android.os.Parcel$LazyValue.apply(Parcel.java:4410)

at android.os.Parcel$LazyValue.apply(Parcel.java:4369)

at

android.os.Base Bundle.getValueAt(BaseBundle.java:394) at android.os.BaseBundle.getValue(BaseBundle.java:374)

at android.os.BaseBundle.getValue(BaseBundle.java:357)

at android.os.BaseBundle.get(BaseBundle.java:696)

at android.os.Bundle.getParcelable(Bundle.java:947)

at o1.b.l(Unknown Source:4)

at 05.W.j(Unknown Source:55)

at 05.W.f(Unknown Source:108)

at b1.g1.e(Unknown Source:76)

at Qa.d0.h(Unknown Source:129)

at Qa.l.invokeSuspend (Unknown Source:11)

at sa.a.resumeWith(Unknown Source:8)

at Na.G.z(Unknown Source:50)

at Na.k.r(Unknown Source:80)

at Na.k.n(Unknown Source:2)

at Pa.g.a(Unknown Source:6)

at Pa.e.G(Unknown Source:73)

at Pa.e.h(Unknown Source:56)

at Pa.e.k(Unknown Source:107)

at e8.c.i(Unknown Source:2)

at com.x8bit.bitwarden.MainActivity.onCreate(Unknown

Source:92)

at android.app.Activity.performCreate(Activity.java:8523) at android.app.Activity.performCreate(Activity.java:8487)

at

android.app.Instrumentation.callActivityOnCreate(Instrume ntation.java:1437) at

android.app.ActivityThread.performLaunchActivity(Activity Thread.java:3853) at

android.app.ActivityThread.handleLaunchActivity(ActivityT hread.java:4018) at

android.app.servertransaction.LaunchActivityItem.execute( LaunchActivityltem.java:101)

at

android.app.servertransaction. Transaction Executor.execut eCallbacks(Transaction Executor.java:135) at

android.app.servertransaction. Transaction Executor.execut e(TransactionExecutor.java:95) at

android.app.ActivityThread$H.handleMessage(ActivityThr ead.java:2427)

at

android.os.Handler.dispatchMessage(Handler.java:106) at android.os.Looper.loopOnce (Looper.java:211) at android.os.Looper.loop (Looper.java:300)

at

android.app.ActivityThread.main(ActivityThread.java:8232) at java.lang.reflect.Method.invoke(Native Method)

at com.android.internal.os.RuntimeInit$MethodAndArgsCalle r.run(RuntimeInit.java:580)

at

com.android.internal.os.ZygoteInit.main(ZygoteInit.java:10 28)

Suppressed:

kotlinx.coroutines.internal.Diagnostic CoroutineContextExc eption: [A0{Cancelling}@7b9de3c,

Dispatchers.Main.immediate]

**Screenshots:**
![Screenshot_2024-09-03-21-30-43-003_com miui bugreport](https://github.com/user-attachments/assets/f19f3b73-86ed-4699-8cf7-5f6460e93264)
![Screenshot_2024-09-03-21-30-38-495_com miui bugreport](https://github.com/user-attachments/assets/c5e2820d-f0a8-42ba-a6f3-6c449ae1f5ca)

### Build Version

© Bitwarden Inc. 2015-2024  Version: 2024.8.0 (18985)

### Environment Details

- Android version: 13
- keyboard: Gboard

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Vstory** [comment]
A crash occurred when using the AutoFill service.



```
Generated by AppErrorsTracking 1.3(6)
Project URL: https://github.com/KitsunePie/AppErrorsTracking
===============
[Device Brand]: Xiaomi
[Device Model]: M2102K1AC
[Display]: TKQ1.220829.002 test-keys
[Android Version]: 13
[Android API Level]: 33
[System Locale]: zh_CN
[Process ID]: 27840
[User ID]: 0
[CPU ABI]: arm64-v8a
[Package Name]: com.x8bit.bitwarden
[Version Name]: 2024.8.0
[Version Code]: 18985
[Target SDK]: 34
[Min SDK]: 28
[Error Type]: JVM
[Crash Time]: 2024-09-01T17:53:06.840
[Stack Trace]:
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Class.isInterface()' on a null object reference
	at java.lang.Class.isAssignableFrom(Class.java:589)
	at android.os.Parcel.readParcelableCreatorInternal(Parcel.java:4853)
	at android.os.Parcel.readParcelableInternal(Parcel.java:4766)
	at android.os.Parcel.readValue(Parcel.java:4532)
	at android.os.Parcel.readValue(Parcel.java:4312)
	at android.os.Parcel.-$$Nest$mreadValue(Unknown Source:0)
	at android.os.Parcel$LazyValue.apply(Parcel.java:4410)
	at android.os.Parcel$LazyValue.apply(Parcel.java:4369)
	at android.os.BaseBundle.getValueAt(BaseBundle.java:394)
	at android.os.BaseBundle.getValue(BaseBundle.java:374)
	at android.os.BaseBundle.getValue(BaseBundle.java:357)
	at android.os.BaseBundle.get(BaseBundle.java:696)
	at android.os.Bundle.getParcelable(Bundle.java:947)
	at o1.b.r(Unknown Source:4)
	at O5.l.invokeSuspend(Unknown Source:66)
	at O5.l.invoke(Unknown Source:12)
	at Na.G.B(Unknown Source:43)
	at c7.c.invokeSuspend(Unknown Source:41)
	at sa.a.resumeWith(Unknown Source:8)
	at Na.O.run(Unknown Source:114)
	at Na.a0.h0(Unknown Source:23)
	at Na.k.r(Unknown Source:83)
	at Na.k.n(Unknown Source:2)
	at Pa.g.a(Unknown Source:6)
	at Pa.e.G(Unknown Source:73)
	at Pa.e.h(Unknown Source:56)
	at Pa.e.k(Unknown Source:107)
	at e8.c.i(Unknown Source:2)
	at com.x8bit.bitwarden.AutofillTotpCopyActivity.onCreate(Unknown Source:52)
	at android.app.Activity.performCreate(Activity.java:8516)
	at android.app.Activity.performCreate(Activity.java:8480)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1418)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3806)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3971)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2389)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8261)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [A0{Cancelling}@afab214, Dispatchers.Main.immediate]
```

**Comment by Greenderella** [comment]
Since this issue has been open for quite some time without recent activity, I'm curious if anyone is still experiencing this problem. If the issue persists, please share any updated details. Thanks, everyone, for your contributions and feedback!

**Comment by Bazixv13** [comment]
Personally I haven’t experienced this issue in a while so I think it’s fixed

**Comment by david-livefront** [comment]
Closing this issue per the comment by @Bazixv13
